"""
VibeBuilder V2 - Export Utilities
For downloading and deploying generated code
"""

import base64
import urllib.parse


def generate_download_link(code: str, filename: str = "vibebuilder_app.html") -> str:
    """
    Generate a download link for the code
    """
    b64 = base64.b64encode(code.encode()).decode()
    return f"data:text/html;base64,{b64}"


def generate_codepen_form(code: str) -> dict:
    """
    Generate data for CodePen export
    
    Returns dict with html, css, js separated
    """
    # Parse the HTML to extract CSS and JS
    html_content = code
    css_content = ""
    js_content = ""
    
    # Extract style content
    import re
    
    style_match = re.search(r'<style[^>]*>(.*?)</style>', code, re.DOTALL | re.IGNORECASE)
    if style_match:
        css_content = style_match.group(1).strip()
    
    script_match = re.search(r'<script[^>]*>(.*?)</script>', code, re.DOTALL | re.IGNORECASE)
    if script_match:
        js_content = script_match.group(1).strip()
    
    # Remove style and script from HTML for CodePen
    html_only = re.sub(r'<style[^>]*>.*?</style>', '', code, flags=re.DOTALL | re.IGNORECASE)
    html_only = re.sub(r'<script[^>]*>.*?</script>', '', html_only, flags=re.DOTALL | re.IGNORECASE)
    html_only = re.sub(r'<!DOCTYPE[^>]*>', '', html_only, flags=re.IGNORECASE)
    html_only = re.sub(r'<html[^>]*>|</html>', '', html_only, flags=re.IGNORECASE)
    html_only = re.sub(r'<head[^>]*>.*?</head>', '', html_only, flags=re.DOTALL | re.IGNORECASE)
    html_only = re.sub(r'<body[^>]*>|</body>', '', html_only, flags=re.IGNORECASE)
    html_only = html_only.strip()
    
    return {
        "html": html_only,
        "css": css_content,
        "js": js_content
    }


def generate_codepen_url(code: str, title: str = "VibeBuilder App") -> str:
    """
    Generate a CodePen prefill URL
    """
    data = generate_codepen_form(code)
    
    # CodePen prefill data format
    prefill = {
        "title": title,
        "description": "Generated by VibeBuilder V2 - Gemini 3 Hackathon",
        "html": data["html"],
        "css": data["css"],
        "js": data["js"],
        "editors": "1111"  # All editors visible
    }
    
    # Encode as JSON for form submission
    import json
    json_str = json.dumps(prefill)
    
    return json_str


def generate_github_gist_content(code: str) -> dict:
    """
    Format code for GitHub Gist
    """
    return {
        "description": "Generated by VibeBuilder V2 - Gemini 3 Hackathon",
        "public": True,
        "files": {
            "index.html": {
                "content": code
            }
        }
    }
